// ============================================================
// BETHESDA AG CHURCH — CENTRALIZED MOCK DATA
// All data structures designed for future Supabase integration
// ============================================================

// ── Images (Unsplash - replaceable with real assets) ──────────
export const IMAGES = {
  hero: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?w=1920&q=80',
  worship1: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1200&q=80',
  worship2: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=1200&q=80',
  church: 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?w=1200&q=80',
  prayer: 'https://images.unsplash.com/photo-1545232979-8bf68ee9b1af?w=1200&q=80',
  community: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&q=80',
  youth: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=1200&q=80',
  kids: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=1200&q=80',
  bible: 'https://images.unsplash.com/photo-1504052434569-70ad5836ab65?w=1200&q=80',
  outreach: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=1200&q=80',
  baptism: 'https://images.unsplash.com/photo-1585241936939-be4099591252?w=1200&q=80',
  concert: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80',
  gathering: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=1200&q=80',
  nature: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=80',
  cross: 'https://images.unsplash.com/photo-1445112098124-3e76dd67983c?w=1200&q=80',
  hands: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80',
  sunset: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=1200&q=80',
  family: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=1200&q=80',
  missions: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&q=80',
  women: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1200&q=80',
  men: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=80',
  logo: '/assets/images/bethesdaag-1785900886399.png',
  logoFull: '/assets/images/app_logo.png',
  placeholder: '/assets/images/no_image.png',
};

// ── Service Times ─────────────────────────────────────────────
export const SERVICE_TIMES = [
  { day: 'Sunday', time: '7:30 AM', name: 'Kannada / Tamil Service', language: 'Kannada / Tamil' },
  { day: 'Sunday', time: '9:30 AM', name: 'Malayalam / Kannada Service', language: 'Malayalam / Kannada' },
  { day: 'Sunday', time: '11:30 AM', name: 'English / Telugu Service', language: 'English / Telugu' },
  { day: 'Sunday', time: '6:30 PM', name: 'Kannada / Hindi Service', language: 'Kannada / Hindi' },
];

// ── Church Info ───────────────────────────────────────────────
export const CHURCH_INFO = {
  name: 'Bethesda AG Church',
  tagline: 'A place to belong. A place to grow. A place to encounter God.',
  address: '36-B, 42nd Cross, 8th Main Rd, 4th Block, Rajajinagar, Bengaluru, Karnataka 560010',
  phone: '+91 98450 09824',
  email: 'contact@bethesdaag.org',
  whatsapp: '919743316337',
  officeHours: 'Mon – Fri: 9:00 AM – 5:00 PM',
  mapUrl: 'https://maps.google.com/?q=Bethesda+AG+Church+Rajajinagar+Bangalore',
  youtubeUrl: 'https://www.youtube.com/@Bethesda_AG',
  youtubeChannelId: '@Bethesda_AG',
  youtubeLiveEmbedUrl: 'https://www.youtube.com/embed/live_stream?channel=@Bethesda_AG',
  social: {
    facebook: 'https://facebook.com/bethesdaagchurch',
    instagram: 'https://instagram.com/bethesdaagchurch',
    youtube: 'https://www.youtube.com/@Bethesda_AG',
    twitter: 'https://twitter.com/bethesdaag',
  },
};

// ── Leaders ───────────────────────────────────────────────────
export const LEADERS = [
  {
    id: 'pastor-samuel',
    name: 'Pastor Samuel Thomas',
    role: 'Senior Pastor',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80',
    bio: 'Pastor Samuel has served Bethesda AG Church for over 20 years, leading with a heart for worship, teaching, and community transformation. His vision is to see every person encounter God\'s love and purpose.',
    email: 'samuel@bethesdaag.org',
  },
  {
    id: 'pastor-grace',
    name: 'Pastor Grace Thomas',
    role: 'Associate Pastor',
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&q=80',
    bio: 'Pastor Grace oversees women\'s ministry, counseling, and community care. Her compassion and wisdom have touched countless lives in the congregation.',
    email: 'grace@bethesdaag.org',
  },
  {
    id: 'pastor-david',
    name: 'Pastor David Joseph',
    role: 'Youth Pastor',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    bio: 'Pastor David leads the youth and young adults ministry with energy and passion. He believes in empowering the next generation to discover their calling.',
    email: 'david@bethesdaag.org',
  },
  {
    id: 'pastor-ruth',
    name: 'Ruth Mathews',
    role: 'Worship Director',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80',
    bio: 'Ruth leads the worship ministry, creating an atmosphere where people can encounter God through music and praise.',
    email: 'ruth@bethesdaag.org',
  },
  {
    id: 'elder-john',
    name: 'John Peter',
    role: 'Church Elder',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80',
    bio: 'Elder John has been a pillar of Bethesda for over 15 years, serving in governance, mentorship, and missions outreach.',
    email: 'john@bethesdaag.org',
  },
  {
    id: 'deacon-mary',
    name: 'Mary Philip',
    role: 'Children\'s Ministry Director',
    image: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=400&q=80',
    bio: 'Mary leads the children\'s ministry with creativity and love, nurturing young hearts in faith and character.',
    email: 'mary@bethesdaag.org',
  },
];

// ── Sermons ───────────────────────────────────────────────────
export const SERMONS = [
  {
    id: 'walking-in-faith',
    slug: 'walking-in-faith',
    title: 'Walking in Faith',
    speaker: 'Pastor Samuel Thomas',
    date: '2026-08-03',
    duration: '42 min',
    series: 'Foundations of Faith',
    category: 'Faith',
    bibleRef: 'Hebrews 11:1-6',
    image: IMAGES.worship1,
    description: 'Discover what it means to live by faith in a world that demands certainty. Pastor Samuel explores the timeless truths of Hebrews 11 and how they apply to our everyday lives.',
    transcript: 'Today I want to talk about faith. Not just the kind we sing about, but the kind that transforms how we live every single day...',
    notes: '1. Faith is the substance of things hoped for\n2. Faith pleases God\n3. Faith requires action\n4. Faith grows through testing',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtubeId: 'dQw4w9WgXcQ',
    audioUrl: '#',
  },
  {
    id: 'the-power-of-prayer',
    slug: 'the-power-of-prayer',
    title: 'The Power of Prayer',
    speaker: 'Pastor Grace Thomas',
    date: '2026-07-27',
    duration: '38 min',
    series: 'Prayer Life',
    category: 'Prayer',
    bibleRef: 'James 5:13-18',
    image: IMAGES.prayer,
    description: 'Prayer is not just a religious exercise — it is the lifeline of every believer. Pastor Grace shares powerful insights on developing a vibrant prayer life.',
    transcript: 'Prayer changes things. I know many of you have heard that before, but today I want us to go deeper...',
    notes: '1. Prayer is our direct line to God\n2. Persistent prayer produces results\n3. Prayer in community multiplies impact',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtubeId: 'dQw4w9WgXcQ',
    audioUrl: '#',
  },
  {
    id: 'identity-in-christ',
    slug: 'identity-in-christ',
    title: 'Identity in Christ',
    speaker: 'Pastor David Joseph',
    date: '2026-07-20',
    duration: '35 min',
    series: 'Who You Are',
    category: 'Identity',
    bibleRef: '2 Corinthians 5:17',
    image: IMAGES.cross,
    description: 'In a world that constantly tries to define who you are, discover your true identity as found in Christ Jesus.',
    transcript: 'Who are you? It\'s a question the world tries to answer for us every day...',
    notes: '1. You are a new creation\n2. Your identity is not in your performance\n3. You are chosen and beloved',
    videoUrl: '#',
    audioUrl: '#',
  },
  {
    id: 'grace-upon-grace',
    slug: 'grace-upon-grace',
    title: 'Grace Upon Grace',
    speaker: 'Pastor Samuel Thomas',
    date: '2026-07-13',
    duration: '40 min',
    series: 'Foundations of Faith',
    category: 'Grace',
    bibleRef: 'John 1:16',
    image: IMAGES.sunset,
    description: 'God\'s grace is not a one-time event but an overflowing river. Dive into the depths of God\'s unmerited favor.',
    transcript: 'Grace. It\'s a word we use so often in church, but do we truly understand its magnitude?...',
    notes: '1. Grace is undeserved favor\n2. Grace empowers us to live differently\n3. Grace is always available',
    videoUrl: '#',
    audioUrl: '#',
  },
  {
    id: 'building-community',
    slug: 'building-community',
    title: 'Building Community',
    speaker: 'Pastor Grace Thomas',
    date: '2026-07-06',
    duration: '36 min',
    series: 'Life Together',
    category: 'Community',
    bibleRef: 'Acts 2:42-47',
    image: IMAGES.community,
    description: 'The early church modeled what authentic community looks like. Learn how we can build deeper connections in our modern world.',
    transcript: 'Community. It\'s not just a buzzword — it\'s God\'s design for how we are meant to live...',
    notes: '1. Community requires intentionality\n2. Vulnerability breeds connection\n3. Serving together strengthens bonds',
    videoUrl: '#',
    audioUrl: '#',
  },
  {
    id: 'purpose-and-calling',
    slug: 'purpose-and-calling',
    title: 'Purpose and Calling',
    speaker: 'Pastor David Joseph',
    date: '2026-06-29',
    duration: '44 min',
    series: 'Who You Are',
    category: 'Purpose',
    bibleRef: 'Jeremiah 29:11',
    image: IMAGES.nature,
    description: 'God has a specific purpose for your life. Discover how to hear His voice and walk in your divine calling.',
    transcript: 'Every single one of you in this room was created with purpose...',
    notes: '1. God\'s plans are for your good\n2. Calling is discovered, not invented\n3. Faithfulness in small things leads to greater purpose',
    videoUrl: '#',
    audioUrl: '#',
  },
];

export const SERMON_SERIES = ['Foundations of Faith', 'Prayer Life', 'Who You Are', 'Life Together'];
export const SERMON_SPEAKERS = ['Pastor Samuel Thomas', 'Pastor Grace Thomas', 'Pastor David Joseph'];
export const SERMON_TOPICS = ['Faith', 'Prayer', 'Identity', 'Grace', 'Community', 'Purpose'];

// ── Events ────────────────────────────────────────────────────
export const EVENTS = [
  {
    id: 'youth-conference-2026',
    slug: 'youth-conference-2026',
    title: 'Youth Conference 2026',
    subtitle: 'ARISE — Igniting the Next Generation',
    date: '2026-09-12',
    endDate: '2026-09-14',
    time: '9:00 AM – 9:00 PM',
    location: 'Bethesda AG Church',
    category: 'Conference',
    image: IMAGES.youth,
    featured: true,
    description: 'Three days of powerful worship, inspiring messages, and life-changing encounters. This annual conference brings together young people from across the region for an unforgettable experience.',
    speakers: ['Pastor David Joseph', 'Guest Speaker TBA'],
    schedule: [
      { day: 'Day 1 — Sept 12', items: ['9:00 AM Registration', '10:00 AM Opening Session', '12:30 PM Lunch', '2:00 PM Workshops', '6:00 PM Evening Rally'] },
      { day: 'Day 2 — Sept 13', items: ['9:00 AM Morning Worship', '10:30 AM Main Session', '12:30 PM Lunch', '2:00 PM Activities', '6:00 PM Evening Rally'] },
      { day: 'Day 3 — Sept 14', items: ['9:00 AM Final Session', '11:00 AM Commissioning', '12:30 PM Closing Lunch'] },
    ],
    registrationOpen: true,
  },
  {
    id: 'prayer-night',
    slug: 'prayer-night',
    title: 'Night of Prayer',
    subtitle: 'Seeking His Face Together',
    date: '2026-08-22',
    time: '7:00 PM – 10:00 PM',
    location: 'Main Sanctuary',
    category: 'Prayer',
    image: IMAGES.prayer,
    featured: false,
    description: 'Join us for an extended time of corporate prayer, worship, and seeking God\'s presence together.',
    speakers: ['Pastor Samuel Thomas'],
    schedule: [],
    registrationOpen: false,
  },
  {
    id: 'womens-retreat',
    slug: 'womens-retreat',
    title: 'Women\'s Retreat',
    subtitle: 'Refresh — Renew — Restore',
    date: '2026-10-03',
    endDate: '2026-10-05',
    time: 'All Day',
    location: 'Hill Country Resort, Coorg',
    category: 'Community',
    image: IMAGES.women,
    featured: false,
    description: 'A weekend getaway designed for women to rest, reconnect with God, and build lasting friendships.',
    speakers: ['Pastor Grace Thomas'],
    schedule: [],
    registrationOpen: true,
  },
  {
    id: 'kids-vbs',
    slug: 'kids-vbs',
    title: 'Vacation Bible School',
    subtitle: 'Adventure Island — Discovering God\'s Truth',
    date: '2026-11-15',
    endDate: '2026-11-20',
    time: '9:00 AM – 1:00 PM',
    location: 'Bethesda AG Church',
    category: 'Kids',
    image: IMAGES.kids,
    featured: false,
    description: 'A fun-filled week of Bible stories, crafts, games, and worship for children ages 5-12.',
    speakers: ['Mary Philip'],
    schedule: [],
    registrationOpen: true,
  },
  {
    id: 'worship-night',
    slug: 'worship-night',
    title: 'Worship Night',
    subtitle: 'An Evening of Praise',
    date: '2026-08-29',
    time: '6:30 PM – 9:00 PM',
    location: 'Main Sanctuary',
    category: 'Worship',
    image: IMAGES.worship2,
    featured: false,
    description: 'An evening dedicated entirely to worship. Come as you are and experience God\'s presence through music and praise.',
    speakers: ['Ruth Mathews'],
    schedule: [],
    registrationOpen: false,
  },
  {
    id: 'community-outreach',
    slug: 'community-outreach',
    title: 'Community Outreach Day',
    subtitle: 'Love in Action',
    date: '2026-09-06',
    time: '8:00 AM – 2:00 PM',
    location: 'Various Locations',
    category: 'Outreach',
    image: IMAGES.outreach,
    featured: false,
    description: 'Join us as we serve our community through practical acts of love and kindness. Multiple service projects available for all ages.',
    speakers: [],
    schedule: [],
    registrationOpen: true,
  },
];

export const EVENT_CATEGORIES = ['All', 'Worship', 'Youth', 'Kids', 'Prayer', 'Conference', 'Outreach', 'Community'];

// ── Ministries ────────────────────────────────────────────────
export const MINISTRIES = [
  {
    id: 'childrens',
    slug: 'childrens',
    name: "Children's Ministry",
    shortDesc: 'Nurturing young hearts in faith, fun, and friendship.',
    description: "Our Children's Ministry provides a safe, engaging environment where children can learn about God's love through age-appropriate teaching, creative activities, and meaningful relationships. From nursery through elementary, every child is valued and loved.",
    image: IMAGES.kids,
    vision: "To raise a generation that knows God's Word, lives with purpose, and impacts the world.",
    leaders: ['Mary Philip'],
    meetingTime: 'Sundays 9:00 AM & 11:00 AM',
    ageGroup: 'Ages 0-12',
  },
  {
    id: 'youth',
    slug: 'youth',
    name: 'Youth Ministry',
    shortDesc: 'Empowering teens to discover their identity and purpose in Christ.',
    description: 'Our Youth Ministry is a vibrant community where teenagers can explore their faith, build lasting friendships, and develop leadership skills. Through worship, small groups, and service projects, we help teens navigate life with biblical foundations.',
    image: IMAGES.youth,
    vision: "To see every young person discover their God-given identity and live boldly for Christ.",
    leaders: ['Pastor David Joseph'],
    meetingTime: 'Fridays 7:00 PM',
    ageGroup: 'Ages 13-18',
  },
  {
    id: 'worship',
    slug: 'worship',
    name: 'Worship Ministry',
    shortDesc: "Leading the congregation into God's presence through music and praise.",
    description: "Our Worship Ministry brings together musicians, vocalists, and tech volunteers who are passionate about creating an atmosphere of authentic worship. We believe worship is more than music — it's a lifestyle of surrender and praise.",
    image: IMAGES.worship1,
    vision: "To create environments where people encounter God's presence through Spirit-led worship.",
    leaders: ['Ruth Mathews'],
    meetingTime: 'Rehearsals: Saturdays 4:00 PM',
    ageGroup: 'All ages',
  },
  {
    id: 'pastoral',
    slug: 'pastoral',
    name: 'Pastoral Ministry',
    shortDesc: 'Shepherding souls with compassion, counsel, and biblical wisdom.',
    description: 'Our Pastoral Ministry is committed to caring for every member of the Bethesda family. Through counseling, visitation, discipleship, and prayer, our pastoral team walks alongside individuals and families in every season of life.',
    image: IMAGES.bible,
    vision: 'To shepherd every soul with the love and wisdom of Christ.',
    leaders: ['Pastor Samuel Thomas', 'Pastor Grace Thomas'],
    meetingTime: 'By appointment',
    ageGroup: 'All ages',
  },
  {
    id: 'evangelism',
    slug: 'evangelism',
    name: 'Evangelism Ministry',
    shortDesc: 'Taking the Good News of Jesus to every street, home, and heart.',
    description: 'Our Evangelism Ministry is passionate about sharing the Gospel with boldness and love. Through outreach programs, street evangelism, door-to-door visits, and community events, we carry the message of hope to those who have not yet heard.',
    image: IMAGES.outreach,
    vision: 'To see every person in our city and beyond encounter the saving grace of Jesus Christ.',
    leaders: ['Pastor Samuel Thomas'],
    meetingTime: 'Saturdays 8:00 AM',
    ageGroup: 'All ages',
  },
  {
    id: 'translation',
    slug: 'translation',
    name: 'Translation Ministry',
    shortDesc: 'Breaking language barriers so all can hear God\'s Word clearly.',
    description: 'Our Translation Ministry ensures that the message of God\'s love is accessible to everyone, regardless of their language. We provide real-time translation and multilingual resources for our diverse congregation spanning Kannada, Tamil, Malayalam, Telugu, Hindi, and English.',
    image: IMAGES.gathering,
    vision: 'To make the Gospel accessible in every tongue spoken among our people.',
    leaders: ['Pastor Samuel Thomas'],
    meetingTime: 'All Sunday services',
    ageGroup: 'All ages',
  },
  {
    id: 'greeters',
    slug: 'greeters',
    name: 'Greeters Ministry',
    shortDesc: 'Welcoming every person who walks through our doors with warmth.',
    description: "Our Greeters Ministry is the first smile every visitor sees. Our dedicated team of welcomers ensures that every person who steps into Bethesda AG Church feels seen, valued, and at home from the moment they arrive.",
    image: IMAGES.community,
    vision: 'To make every person feel genuinely welcomed and loved from their very first step.',
    leaders: ['John Peter'],
    meetingTime: 'Every Sunday service',
    ageGroup: 'All ages',
  },
  {
    id: 'hospitality',
    slug: 'hospitality',
    name: 'Hospitality Ministry',
    shortDesc: 'Creating a warm, welcoming atmosphere through fellowship and care.',
    description: 'Our Hospitality Ministry serves the congregation and guests through the gift of fellowship. From preparing refreshments and meals for church events to organizing fellowship gatherings, this team reflects the warmth and generosity of Christ.',
    image: IMAGES.family,
    vision: "To reflect Christ's love through genuine hospitality, making every gathering a celebration of community.",
    leaders: ['Pastor Grace Thomas'],
    meetingTime: 'All church events',
    ageGroup: 'All ages',
  },
  {
    id: 'facilities',
    slug: 'facilities',
    name: 'Facilities & Maintenance Ministry',
    shortDesc: 'Keeping our house of God beautiful, safe, and ready for worship.',
    description: 'Our Facilities & Maintenance Ministry is the backbone of our physical church operations. This dedicated team ensures our worship spaces, classrooms, and grounds are always clean, well-maintained, and prepared to welcome the congregation.',
    image: IMAGES.cross,
    vision: "To honor God by caring excellently for the space where His people gather.",
    leaders: ['John Peter'],
    meetingTime: 'Weekly service',
    ageGroup: 'All ages',
  },
  {
    id: 'media',
    slug: 'media',
    name: 'Media Ministry',
    shortDesc: 'Amplifying God\'s message through technology, sound, and visuals.',
    description: "Our Media Ministry handles all audio, video, photography, live streaming, and digital communication for Bethesda AG Church. From Sunday services to special events, this team works tirelessly behind the scenes to ensure every message is heard clearly and reaches far beyond our walls.",
    image: IMAGES.concert,
    vision: 'To use technology and creativity as powerful tools to spread the Gospel to every corner of the world.',
    leaders: ['Ruth Mathews'],
    meetingTime: 'All Sunday services & events',
    ageGroup: 'All ages',
  },
  {
    id: 'prayer',
    slug: 'prayer-ministry',
    name: 'Prayer Ministry',
    shortDesc: 'Interceding for the church, community, and nations.',
    description: 'Our Prayer Ministry is the backbone of everything we do. We believe in the power of corporate and individual prayer to transform lives, heal the broken, and advance God\'s kingdom.',
    image: IMAGES.prayer,
    vision: 'To be a house of prayer for all nations.',
    leaders: ['Pastor Samuel Thomas'],
    meetingTime: 'Wednesdays 7:00 PM, Daily 6:00 AM',
    ageGroup: 'All ages',
  },
];

// ── Testimonials ──────────────────────────────────────────────
export const TESTIMONIALS = [
  {
    id: 'test-1',
    name: 'Priya Sharma',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    testimony: 'Bethesda AG Church has been my spiritual home for the past five years. The warmth, the teaching, and the genuine love of this community have transformed my life. I walked in broken and found healing through God\'s grace and the support of this family.',
    date: '2026-06-15',
    category: 'Healing',
  },
  {
    id: 'test-2',
    name: 'Rahul Menon',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    testimony: 'As a young professional new to Bangalore, I was searching for community. The youth ministry at Bethesda not only welcomed me but gave me a family. I\'ve grown in faith and purpose more in the last two years than I ever imagined possible.',
    date: '2026-05-22',
    category: 'Community',
  },
  {
    id: 'test-3',
    name: 'Anita Thomas',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80',
    testimony: 'The women\'s ministry helped me through the most difficult season of my life. The prayer support, mentorship, and biblical teaching gave me strength I didn\'t know I had. God is faithful, and this church lives that truth.',
    date: '2026-04-10',
    category: 'Faith',
  },
  {
    id: 'test-4',
    name: 'Daniel Raj',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80',
    testimony: 'My family was going through a crisis when we first visited Bethesda. The pastors prayed with us, the congregation embraced us, and God did a miracle in our marriage. We\'ve been serving here ever since.',
    date: '2026-03-18',
    category: 'Restoration',
  },
];

// ── Small Groups ──────────────────────────────────────────────
export const SMALL_GROUPS = [
  {
    id: 'sg-1',
    name: 'Faith Builders',
    day: 'Tuesday',
    time: '7:00 PM',
    location: 'Rajajinagar',
    leader: 'John Peter',
    type: 'Bible Study',
    ageGroup: 'Adults',
    description: 'A deep-dive Bible study group exploring Scripture together.',
    spotsAvailable: 4,
  },
  {
    id: 'sg-2',
    name: 'Young Professionals',
    day: 'Wednesday',
    time: '7:30 PM',
    location: 'Malleswaram',
    leader: 'Pastor David Joseph',
    type: 'Fellowship',
    ageGroup: 'Young Adults',
    description: 'A community for working professionals navigating faith and career.',
    spotsAvailable: 6,
  },
  {
    id: 'sg-3',
    name: 'Couples Connect',
    day: 'Friday',
    time: '7:00 PM',
    location: 'Basaveshwaranagar',
    leader: 'Pastor Samuel Thomas',
    type: 'Marriage',
    ageGroup: 'Couples',
    description: 'Growing stronger marriages through biblical principles.',
    spotsAvailable: 2,
  },
  {
    id: 'sg-4',
    name: 'Women of the Word',
    day: 'Thursday',
    time: '10:00 AM',
    location: 'Church Campus',
    leader: 'Pastor Grace Thomas',
    type: 'Bible Study',
    ageGroup: 'Women',
    description: 'Women digging deep into God\'s Word together.',
    spotsAvailable: 8,
  },
  {
    id: 'sg-5',
    name: 'Kingdom Warriors',
    day: 'Saturday',
    time: '6:00 AM',
    location: 'Church Campus',
    leader: 'John Peter',
    type: 'Prayer',
    ageGroup: 'Men',
    description: 'Men committed to prayer, accountability, and growth.',
    spotsAvailable: 5,
  },
];

// ── Blog Posts ─────────────────────────────────────────────────
export const BLOG_POSTS = [
  {
    id: 'finding-peace',
    slug: 'finding-peace-in-uncertain-times',
    title: 'Finding Peace in Uncertain Times',
    excerpt: 'In a world filled with uncertainty, God\'s peace remains our anchor. Discover how to cultivate inner peace through faith and trust.',
    content: 'Life has a way of throwing unexpected challenges our way. Whether it\'s a health crisis, financial difficulty, or relational struggle, uncertainty can shake us to our core.\n\nBut Scripture reminds us: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid." (John 14:27)\n\nHere are three practical ways to cultivate peace in uncertain times:\n\n**1. Anchor Your Mind in Scripture**\nWhen anxiety rises, return to God\'s promises. His Word is the foundation that does not shift.\n\n**2. Practice Gratitude Daily**\nGratitude redirects our focus from what we lack to what God has already provided.\n\n**3. Lean Into Community**\nYou were never meant to walk through difficulty alone. Share your burdens with trusted believers.',
    author: 'Pastor Samuel Thomas',
    date: '2026-08-05',
    category: 'Faith',
    image: IMAGES.nature,
    readTime: '5 min read',
    featured: true,
  },
  {
    id: 'power-of-worship',
    slug: 'the-power-of-worship-beyond-sunday',
    title: 'The Power of Worship Beyond Sunday',
    excerpt: 'Worship isn\'t limited to Sunday mornings. Learn how to make worship a lifestyle that transforms every area of your life.',
    content: 'When we think of worship, we often picture a Sunday morning service — the band playing, hands raised, voices singing. And while corporate worship is powerful and essential, God invites us into something much more expansive.\n\nWorship is a lifestyle. It\'s how we respond to God in every moment of every day.',
    author: 'Ruth Mathews',
    date: '2026-07-28',
    category: 'Devotional',
    image: IMAGES.worship2,
    readTime: '4 min read',
    featured: false,
  },
  {
    id: 'raising-faithful-kids',
    slug: 'raising-faithful-kids-in-digital-age',
    title: 'Raising Faithful Kids in a Digital Age',
    excerpt: 'Navigate the challenges of parenting in the digital era while grounding your children in biblical values and authentic faith.',
    content: 'Parenting has always been challenging, but the digital age adds layers of complexity that previous generations never faced. How do we raise children who love God in a world that\'s constantly vying for their attention?',
    author: 'Mary Philip',
    date: '2026-07-20',
    category: 'Family',
    image: IMAGES.family,
    readTime: '6 min read',
    featured: false,
  },
  {
    id: 'missions-heart',
    slug: 'developing-a-missions-heart',
    title: 'Developing a Missions Heart',
    excerpt: 'God\'s heart beats for the nations. Discover how you can participate in the Great Commission from right where you are.',
    content: 'Missions isn\'t just for missionaries. Every believer is called to participate in God\'s global mission — whether through prayer, giving, going, or sending.',
    author: 'Pastor Samuel Thomas',
    date: '2026-07-12',
    category: 'Missions',
    image: IMAGES.missions,
    readTime: '5 min read',
    featured: false,
  },
  {
    id: 'youth-identity',
    slug: 'identity-crisis-and-the-gospel',
    title: 'Identity Crisis and the Gospel',
    excerpt: 'Young people today face an identity crisis. The Gospel offers a radical answer to the question, "Who am I?"',
    content: 'In an age of social media, peer pressure, and cultural confusion, young people are struggling with the fundamental question of identity more than ever before.',
    author: 'Pastor David Joseph',
    date: '2026-07-05',
    category: 'Youth',
    image: IMAGES.youth,
    readTime: '4 min read',
    featured: false,
  },
  {
    id: 'prayer-guide',
    slug: 'a-simple-guide-to-daily-prayer',
    title: 'A Simple Guide to Daily Prayer',
    excerpt: 'Struggling with your prayer life? Here\'s a simple, practical framework to help you connect with God daily.',
    content: 'Many believers struggle with consistency in prayer. It\'s not that we don\'t want to pray — it\'s that we don\'t always know how to sustain a meaningful prayer life.',
    author: 'Pastor Grace Thomas',
    date: '2026-06-28',
    category: 'Devotional',
    image: IMAGES.bible,
    readTime: '3 min read',
    featured: false,
  },
];

export const BLOG_CATEGORIES = ['All', 'Faith', 'Devotional', 'Family', 'Youth', 'Church', 'Missions', 'Announcements'];

// ── Devotionals ───────────────────────────────────────────────
export const DEVOTIONALS = [
  {
    id: 'dev-1',
    date: '2026-08-10',
    title: 'Rest in His Presence',
    scripture: 'Psalm 46:10 — "Be still, and know that I am God."',
    reflection: 'In the hustle of daily life, God invites us to pause. Stillness isn\'t about doing nothing — it\'s about positioning our hearts to hear His voice. Today, take five minutes to simply sit in God\'s presence without an agenda. Let Him speak to your heart.',
    prayer: 'Lord, teach me to be still. In the noise and demands of life, help me find my rest in You. Quiet my anxious thoughts and fill me with Your peace. Amen.',
  },
  {
    id: 'dev-2',
    date: '2026-08-09',
    title: 'Strength for Today',
    scripture: 'Isaiah 40:31 — "But those who hope in the Lord will renew their strength."',
    reflection: 'Weariness is real. Whether it\'s physical, emotional, or spiritual, there are seasons when we feel depleted. But God\'s promise is renewal — not on our timetable, but His. The invitation is to wait with expectation, trusting that fresh strength is coming.',
    prayer: 'Father, I bring my weariness before You. Renew my strength as I place my hope in You. Give me wings like eagles to rise above my circumstances. Amen.',
  },
  {
    id: 'dev-3',
    date: '2026-08-08',
    title: 'Chosen and Loved',
    scripture: '1 Peter 2:9 — "You are a chosen people, a royal priesthood."',
    reflection: 'Before you accomplished anything, God chose you. Your worth isn\'t determined by productivity, popularity, or performance. You are chosen. You are loved. Let this truth anchor you today.',
    prayer: 'God, thank You for choosing me. Help me live from a place of identity rather than striving. I am Yours, and that is enough. Amen.',
  },
];

// ── Gallery Items ─────────────────────────────────────────────
export const GALLERY_ITEMS = [
  { id: 'g1', image: IMAGES.worship1, category: 'Worship', caption: 'Sunday Celebration Service' },
  { id: 'g2', image: IMAGES.youth, category: 'Youth', caption: 'Youth Fellowship Night' },
  { id: 'g3', image: IMAGES.kids, category: 'Kids', caption: 'Children\'s Sunday School' },
  { id: 'g4', image: IMAGES.community, category: 'Community', caption: 'Church Picnic 2026' },
  { id: 'g5', image: IMAGES.prayer, category: 'Worship', caption: 'Night of Prayer' },
  { id: 'g6', image: IMAGES.outreach, category: 'Outreach', caption: 'Community Service Day' },
  { id: 'g7', image: IMAGES.worship2, category: 'Worship', caption: 'Christmas Eve Service' },
  { id: 'g8', image: IMAGES.gathering, category: 'Community', caption: 'Small Group Gathering' },
  { id: 'g9', image: IMAGES.baptism, category: 'Events', caption: 'Water Baptism Service' },
  { id: 'g10', image: IMAGES.concert, category: 'Events', caption: 'Worship Conference 2026' },
  { id: 'g11', image: IMAGES.family, category: 'Community', caption: 'Family Sunday' },
  { id: 'g12', image: IMAGES.bible, category: 'Youth', caption: 'Bible Study Group' },
];

export const GALLERY_CATEGORIES = ['All', 'Worship', 'Youth', 'Kids', 'Events', 'Outreach', 'Community'];

// ── Admin Dashboard Stats ─────────────────────────────────────
export const ADMIN_STATS = {
  visitors: { value: 12847, change: '+12.5%', trend: 'up' as const },
  prayerRequests: { value: 48, change: '+8.3%', trend: 'up' as const },
  eventRegistrations: { value: 234, change: '+22.1%', trend: 'up' as const },
  upcomingEvents: { value: 6, change: '0', trend: 'neutral' as const },
  sermonViews: { value: 5621, change: '+15.7%', trend: 'up' as const },
  donations: { value: 185000, change: '+5.2%', trend: 'up' as const },
};

export const ADMIN_CHART_DATA = {
  visitors: [
    { month: 'Jan', value: 8200 }, { month: 'Feb', value: 9100 }, { month: 'Mar', value: 9800 },
    { month: 'Apr', value: 10400 }, { month: 'May', value: 11200 }, { month: 'Jun', value: 11800 },
    { month: 'Jul', value: 12300 }, { month: 'Aug', value: 12847 },
  ],
  sermonViews: [
    { month: 'Jan', value: 3200 }, { month: 'Feb', value: 3800 }, { month: 'Mar', value: 4100 },
    { month: 'Apr', value: 4500 }, { month: 'May', value: 4900 }, { month: 'Jun', value: 5100 },
    { month: 'Jul', value: 5400 }, { month: 'Aug', value: 5621 },
  ],
  donations: [
    { month: 'Jan', value: 145000 }, { month: 'Feb', value: 152000 }, { month: 'Mar', value: 148000 },
    { month: 'Apr', value: 165000 }, { month: 'May', value: 170000 }, { month: 'Jun', value: 175000 },
    { month: 'Jul', value: 180000 }, { month: 'Aug', value: 185000 },
  ],
  events: [
    { month: 'Jan', value: 120 }, { month: 'Feb', value: 145 }, { month: 'Mar', value: 165 },
    { month: 'Apr', value: 180 }, { month: 'May', value: 195 }, { month: 'Jun', value: 210 },
    { month: 'Jul', value: 225 }, { month: 'Aug', value: 234 },
  ],
};

// ── Member mock data ──────────────────────────────────────────
export const MOCK_MEMBER = {
  id: 'member-1',
  name: 'Sarah Johnson',
  email: 'sarah@example.com',
  phone: '+91 98765 43210',
  image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
  memberSince: '2022-03-15',
  groups: ['Faith Builders', 'Women of the Word'],
  savedSermons: ['walking-in-faith', 'the-power-of-prayer'],
  givingHistory: [
    { date: '2026-08-01', amount: 2500, type: 'Monthly' },
    { date: '2026-07-01', amount: 2500, type: 'Monthly' },
    { date: '2026-06-15', amount: 5000, type: 'One Time' },
    { date: '2026-06-01', amount: 2500, type: 'Monthly' },
  ],
};

// ── AI Chat mock responses ────────────────────────────────────
export const AI_RESPONSES: Record<string, string> = {
  'What time is Sunday service?': 'Our Sunday services are at 9:00 AM (English Celebration Service), 11:00 AM (Kannada Worship), and 6:30 PM (Evening Service - Multilingual). We\'d love to see you there!',
  'Where is the church?': 'Bethesda AG Church is located at 36-B, 42nd Cross, 8th Main Rd, 4th Block, Rajajinagar, Bengaluru, Karnataka 560010. We have parking available on campus. See you soon!',
  'How can I request prayer?': 'You can submit a prayer request through our Prayer page at /prayer. You can choose to remain anonymous if you prefer. Our prayer team prays over every request received. We\'re here for you.',
  'How do I register for an event?': 'Visit our Events page at /events to see all upcoming events. Click on any event to see details and register. Registration is quick and easy!',
  'What ministries are available?': 'We have ministries for everyone! Kids, Youth, Young Adults, Men, Women, Worship, Prayer, Missions, and Community Outreach. Visit /ministries to learn more about each one and find where you belong.',
};

export const AI_SUGGESTIONS = [
  'What time is Sunday service?',
  'Where is the church?',
  'How can I request prayer?',
  'How do I register for an event?',
  'What ministries are available?',
];

// ── Visit page data ───────────────────────────────────────────
export const VISIT_CARDS = [
  { icon: 'Clock', title: 'Service Times', description: 'Sundays at 7:30 AM, 9:30 AM, 11:30 AM, 6:30 PM.' },
  { icon: 'MapPin', title: 'Location', description: 'Rajajinagar, Bengaluru. Easy access from major roads with clear signage.' },
  { icon: 'Car', title: 'Parking', description: 'Free parking available on campus. Overflow parking nearby with shuttle service on Sundays.' },
  { icon: 'Baby', title: 'Kids', description: 'Safe, fun children\'s programs available during all services for ages 0-12.' },
  { icon: 'Accessibility', title: 'Accessibility', description: 'Wheelchair accessible facilities, hearing assistance, and reserved seating available.' },
  { icon: 'Heart', title: 'What to Expect', description: 'Warm welcome, contemporary worship, biblical teaching, and genuine community. Come as you are!' },
];

// ── Resource cards ────────────────────────────────────────────
export const RESOURCES = [
  { icon: 'BookOpen', title: 'Bible', description: 'Read and study Scripture online.', href: '#' },
  { icon: 'Sunrise', title: 'Devotionals', description: 'Daily reflections to start your day.', href: '/resources/devotionals' },
  { icon: 'FileText', title: 'Sermon Notes', description: 'Download notes from recent messages.', href: '/messages' },
  { icon: 'Download', title: 'Downloads', description: 'Free resources for growth.', href: '#' },
];

// ── Beliefs ───────────────────────────────────────────────────
export const BELIEFS = [
  { title: 'The Bible', description: 'We believe the Bible is the inspired, infallible Word of God — our ultimate authority for faith and practice.' },
  { title: 'God', description: 'We believe in one God, eternally existing in three persons: Father, Son, and Holy Spirit.' },
  { title: 'Jesus Christ', description: 'We believe in the deity of Jesus Christ, His virgin birth, sinless life, atoning death, bodily resurrection, and coming return.' },
  { title: 'The Holy Spirit', description: 'We believe in the present ministry of the Holy Spirit who empowers believers for godly living and service.' },
  { title: 'Salvation', description: 'We believe salvation is a gift of God\'s grace received through faith in Jesus Christ alone.' },
  { title: 'The Church', description: 'We believe the Church is the body of Christ, called to worship, fellowship, discipleship, and mission.' },
];

// ── Church History Timeline ───────────────────────────────────
export const TIMELINE = [
  { year: '1985', title: 'Church Founded', description: 'Bethesda AG Church was founded as a small house fellowship in Rajajinagar with just 12 members.' },
  { year: '1992', title: 'First Building', description: 'The congregation moved into its first dedicated worship space, marking a new chapter of growth.' },
  { year: '2001', title: 'Multilingual Ministry', description: 'Services expanded to include Kannada, Tamil, and English, welcoming the diverse community of Bangalore.' },
  { year: '2010', title: 'Youth Revolution', description: 'The youth ministry launched with a vision to raise the next generation of leaders for Christ.' },
  { year: '2018', title: 'Community Outreach', description: 'Major community outreach programs began, serving thousands in the local community annually.' },
  { year: '2024', title: 'Digital Ministry', description: 'Online services and digital ministry platforms launched, reaching people beyond geographical boundaries.' },
  { year: '2026', title: 'Building the Future', description: 'Continuing to grow, serve, and transform lives for the glory of God.' },
];

// ── Values ────────────────────────────────────────────────────
export const VALUES = [
  { title: 'Worship', description: 'We exist to glorify God through passionate, Spirit-led worship.' },
  { title: 'Community', description: 'We are committed to authentic relationships and genuine fellowship.' },
  { title: 'Discipleship', description: 'We invest in spiritual growth through biblical teaching and mentoring.' },
  { title: 'Service', description: 'We serve others with humility, reflecting the heart of Jesus.' },
  { title: 'Mission', description: 'We are passionate about sharing the Gospel locally and globally.' },
  { title: 'Generosity', description: 'We live openhanded lives, giving freely of our time, talents, and resources.' },
];
